services:
  - type: web
    name: nesako-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
